version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-latest

sphinx:
   configuration: docs/conf.py

conda:
  environment: docs/environment.yaml

formats:
  - pdf
  - epub
