channels:
  - conda-forge
  - defaults
dependencies:
  - numpy>2.0
  - scipy
  - future
  - click
  - tqdm
  - pyyaml
  - astropy>=5
  - methodtools
  - pyuvdata
  - cached_property
  - rich
  - attrs
  - sphinx>=5.0
  - numpydoc
  - nbsphinx
  - ipython
  - pandoc
  - pip
  - python=3.10
  - setuptools_scm
  - matplotlib
  - pip:
    - furo
    - lunarsky>=0.2.5
    - sphinx_design
    - 21cmSense>=2.2.1
